import { useEffect, useState } from 'react'
import Navbar from '../components/Navbar.jsx'
const API_URL = import.meta.env.VITE_API_URL || 'http://localhost:5000'
const SendIcon = () => <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round"><path d="M5 12h14m-6-6 6 6-6 6" /></svg>

export default function Contact() {
  const [form, setForm] = useState({ name: '', email: '', message: '' }); const [status, setStatus] = useState({}); const [sending, setSending] = useState(false); const [darkMode, setDarkMode] = useState(() => localStorage.getItem('jay-theme') !== 'light'); useEffect(() => localStorage.setItem('jay-theme', darkMode ? 'dark' : 'light'), [darkMode])
  async function submit(event) { event.preventDefault(); setSending(true); setStatus({}); try { const response = await fetch(`${API_URL}/api/contact`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(form) }); const data = await response.json(); if (!response.ok) throw new Error(data.message); setStatus({ ok: true, text: data.message }); setForm({ name: '', email: '', message: '' }) } catch (error) { setStatus({ text: error.message || 'Unable to send your message.' }) } finally { setSending(false) } }
  const input = `w-full rounded-lg border bg-white p-2.5 text-sm text-zinc-950 outline-none placeholder:text-zinc-400 focus:ring-2 ${darkMode ? 'border-zinc-600 bg-zinc-800 text-zinc-100 focus:border-zinc-200 focus:ring-zinc-100/10' : 'border-zinc-300 focus:border-black focus:ring-black/10'}`; const card = darkMode ? 'border-zinc-700 bg-zinc-900' : 'border-zinc-200 bg-white'
  return <main className={`flex min-h-[100dvh] flex-col ${darkMode ? 'bg-[#171716] text-zinc-100' : 'bg-[#f7f7f4] text-zinc-950'}`}><Navbar darkMode={darkMode} onToggleTheme={() => setDarkMode(!darkMode)} active="Contact" /><section className={`mx-auto my-3 flex w-[min(100%-32px,620px)] flex-1 flex-col justify-center rounded-2xl border px-5 py-6 shadow-xl sm:px-8 sm:py-5 ${card}`}><p className="mb-1 text-[10px] font-bold uppercase tracking-[.1em] text-zinc-500">Let&apos;s work together</p><h1 className="text-3xl font-bold leading-none tracking-[-.065em] sm:text-4xl">Get in touch.</h1><p className={`my-2 text-[13px] leading-relaxed ${darkMode ? 'text-zinc-300' : 'text-zinc-600'}`}>Have a project in mind? Send me a message.</p><form onSubmit={submit} className="grid gap-2"><label className="grid gap-1 text-xs font-bold">Name<input className={input} value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} required /></label><label className="grid gap-1 text-xs font-bold">Email<input className={input} type="email" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} required /></label><label className="grid gap-1 text-xs font-bold">Message<textarea className={input} rows="2" value={form.message} onChange={(e) => setForm({ ...form, message: e.target.value })} required /></label><button className="flex w-fit items-center gap-2 rounded-lg bg-black px-4 py-2 text-xs font-bold text-white disabled:opacity-60" disabled={sending}>{sending ? 'Sending...' : <>Send message <SendIcon /></>}</button>{status.text && <p className={status.ok ? 'text-xs text-green-600' : 'text-xs text-red-600'}>{status.text}</p>}</form></section></main>
}
