import { useEffect, useState } from 'react'
import Navbar from './components/Navbar.jsx'
import profileImage from './assets/ako.png'

const PinIcon = () => <svg className="h-3 w-3" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M20 10c0 5-8 11-8 11S4 15 4 10a8 8 0 1 1 16 0Z" /><circle cx="12" cy="10" r="2" /></svg>
const CheckIcon = () => <svg className="h-3 w-3" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="m5 12 4 4L19 6" /></svg>
const DownloadIcon = () => <svg className="h-3 w-3" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M12 3v12m0 0 4-4m-4 4-4-4M4 21h16" /></svg>

function HeroArt() { return <div className="mx-auto h-[340px] w-full max-w-[390px] overflow-hidden rounded-[36px] bg-zinc-900"><img src={profileImage} alt="Jay Comendador" className="h-full w-full object-cover object-center" /></div> }

export default function App() {
  const [darkMode, setDarkMode] = useState(() => localStorage.getItem('jay-theme') === 'dark'); useEffect(() => localStorage.setItem('jay-theme', darkMode ? 'dark' : 'light'), [darkMode])
  return <main className={`min-h-screen ${darkMode ? 'bg-[#171716] text-zinc-100' : 'bg-white text-zinc-950'}`}><Navbar darkMode={darkMode} onToggleTheme={() => setDarkMode(!darkMode)} /><section className="mx-auto grid min-h-[calc(100vh-64px)] w-[min(100%-42px,990px)] grid-cols-1 items-center gap-8 py-10 lg:grid-cols-[47%_53%] lg:py-6"><div className="max-w-[410px]"><span className={`inline-flex items-center gap-1 rounded-full px-2 py-1 text-[10px] ${darkMode ? 'bg-zinc-800' : 'bg-zinc-100'}`}><i className="h-1.5 w-1.5 rounded-full bg-green-500" />Available for freelance work</span><h1 className="mt-6 text-5xl font-extrabold leading-[.98] tracking-[-.065em] sm:text-6xl">Hi, I&apos;m Jay<br />Comendador</h1><h2 className="mt-4 font-serif text-3xl font-bold">Frontend Developer<span className="font-sans font-normal">|</span></h2><p className={`mt-3 text-xs leading-relaxed ${darkMode ? 'text-zinc-300' : 'text-zinc-700'}`}>I create beautiful, functional, and user-centered digital experiences. 4th Year College in Northwest Samar State University, I bring ideas to life through clean code and thoughtful design.</p><div className="mt-4 flex flex-wrap gap-x-5 gap-y-2 text-[10px]"><span className="flex items-center gap-1"><PinIcon />Based in Samar, Calbayog City</span><span className="flex items-center gap-1"><CheckIcon />Available Now</span></div><div className="mt-4 flex gap-2"><a href="/contact" className={`rounded-md px-3 py-2 text-[10px] ${darkMode ? 'bg-white text-black' : 'bg-black text-white'}`}>Hire Me</a><a href="/contact" className="flex items-center gap-1 rounded-md border border-current px-3 py-2 text-[10px]">Download CV <DownloadIcon /></a></div></div><HeroArt /></section><section id="about" /><section id="projects" /><section id="services" /></main>
}
