import { Pencil } from 'lucide-react';
import profile from '../../../public/profile.png';

export default function DashboardPage({ content, projects, onNavigate, onEdit }) {
  return <div className="dashboard-grid"><section className="dashboard-main"><div className="stats-row"><article className="earning-card"><small>Portfolio progress</small><strong>86<span>%</span></strong><p><i /> 10% since last month</p></article><div className="mini-stat-group"><article><b>04</b><div><strong>Projects</strong><span>published</span></div></article><article><b>12</b><div><strong>Skills</strong><span>in your stack</span></div></article></div></div><section className="dashboard-section"><div className="section-heading"><h2>Recent Projects</h2><button onClick={() => onNavigate('Projects')}>View all</button></div><div className="project-list">{projects.slice(0, 3).map((project) => <Project key={project.name} {...project} />)}</div></section><section className="dashboard-banner"><span>&lt;/&gt;</span><div><strong>Ready to share your next project?</strong><p>Keep your portfolio fresh and up to date.</p></div><button onClick={onEdit}><Pencil size={14} /> Edit portfolio</button></section></section><aside className="dashboard-right"><section className="dashboard-section"><div className="section-heading"><h2>Your Projects</h2><button onClick={() => onNavigate('Projects')}>See all projects</button></div>{projects.slice(0, 2).map((project) => <Mini key={project.name} {...project} />)}</section><section className="recommendation"><div className="recommendation-owner"><img src={profile} alt="" /><span><strong>Portfolio insights</strong><small>Updated just now</small></span><b>Tip</b></div><h2>Showcase your best work.</h2><p>Add a recent project or refresh your introduction so visitors can quickly see what you do.</p><div className="recommendation-footer"><strong>{content.projects} projects</strong><button onClick={onEdit}>Update</button></div></section></aside></div>;
}

function Project({ name, detail, status }) { return <article className="project-row"><img src={profile} alt="" /><div><strong>{name}</strong><span>{detail}</span></div><em className={status.toLowerCase().replace(' ', '-')}>{status}</em></article>; }
function Mini({ name, detail }) { return <div className="side-project"><img src={profile} alt="" /><div><strong>{name}</strong><span>{detail}</span></div></div>; }
