import { Mail, Search, Send, Trash2 } from 'lucide-react';
import { useMemo, useState } from 'react';

export default function MessagesPage({ messages, status, onDelete }) {
  const [selectedId, setSelectedId] = useState(null); const [query, setQuery] = useState(''); const [deleting, setDeleting] = useState(false); const [error, setError] = useState('');
  const filteredMessages = useMemo(() => messages.filter((message) => `${message.name} ${message.email}`.toLowerCase().includes(query.toLowerCase())), [messages, query]);
  const selected = messages.find((message) => message._id === selectedId) || filteredMessages[0];
  const deleteSelected = async () => {
    if (!selected || !window.confirm(`Delete the full conversation with ${selected.name}?`)) return;
    setDeleting(true); setError('');
    try { await onDelete(selected._id); setSelectedId(null); } catch (requestError) { setError(requestError.message); } finally { setDeleting(false); }
  };
  return <section className="dashboard-panel messages-page"><div className="panel-heading"><div><p className="dashboard-kicker">INBOX</p><h2>Messages</h2></div><span className="message-count">{messages.length} received</span></div><div className="messages-layout"><aside className="message-list"><label className="message-search"><Search size={15} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search senders" /></label>{status === 'loading' && <p className="message-list-state">Loading messages…</p>}{status === 'unavailable' && <p className="message-list-state">Messages are unavailable until the server and database are connected.</p>}{status === 'ready' && !filteredMessages.length && <p className="message-list-state">No messages found.</p>}{filteredMessages.map((message) => <button type="button" key={message._id} className={selected?._id === message._id ? 'message-preview selected' : 'message-preview'} onClick={() => setSelectedId(message._id)}><Avatar sender={message} /><span><strong>{message.name}</strong><small>{message.email}</small><em>{message.message}</em></span><time>{formatDate(message.createdAt)}</time></button>)}</aside><article className="message-conversation">{selected ? <><header><Avatar sender={selected} /><div><strong>{selected.name}</strong><span>{selected.email}</span></div></header><div className="message-body"><p>{selected.message}</p><time>{new Date(selected.createdAt).toLocaleString()}</time></div>{error && <p className="message-delete-error">{error}</p>}<div className="message-actions"><a className="message-reply" href={`mailto:${selected.email}?subject=${encodeURIComponent('Re: your portfolio message')}`}><Mail size={15} /> Reply by email <Send size={14} /></a><button className="message-delete" type="button" disabled={deleting} onClick={deleteSelected}><Trash2 size={15} /> {deleting ? 'Deleting…' : 'Delete conversation'}</button></div></> : <div className="message-empty"><Mail size={28} /><strong>Select a sender</strong><span>Messages from your portfolio contact form will appear here.</span></div>}</article></div></section>;
}

function Avatar({ sender }) { const initial = (sender.name || sender.email || '?').trim().slice(0, 1).toUpperCase(); return sender.profileImage ? <img className="sender-avatar" src={sender.profileImage} alt={`${sender.name}'s profile`} /> : <span className="sender-avatar sender-initial" aria-label={`${sender.name} has no profile image`}>{initial}</span>; }
function formatDate(value) { const date = new Date(value); return Number.isNaN(date.getTime()) ? '' : date.toLocaleDateString(undefined, { month: 'short', day: 'numeric' }); }
